from .home import home
from .sidebar import sidebar
from .detection import detection
from .analytics import analytics
from .prediction import prediction
from .monitoring import monitoring
from .signals import signals
from .reports import reports
from .settings import settings
from .about import about